---
name: Continuous Integration
on:
  workflow_call:

jobs:
  validate:
    name: Validate Bicep
    runs-on:
      self-hosted
    environment: alz-r52510r569-plan
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: Install Bicep and Update Az Module
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-installer@main

      - name: Check for Custom Modules
        shell: pwsh
        working-directory: config
        run: |
          if (Test-Path -Path ./custom-modules/*)
          {
            echo "CUSTOM_MODULES=true" >> $env:GITHUB_ENV
            echo "Set CUSTOM_MODULES to true"
          }
          else
          {
            echo "Set CUSTOM_MODULES to false"
          }

      - name: Bicep Build & Lint All Custom Modules
        shell: pwsh
        if: ${{ env.CUSTOM_MODULES == 'true' }}
        working-directory: config/custom-modules
        run: |
          $output = @()
          Get-ChildItem -Recurse -Filter '*.bicep' | ForEach-Object {
              Write-Information "==> Attempting Bicep Build For File: $_" -InformationAction Continue
              $bicepOutput = bicep build $_.FullName 2>&1
              if ($LastExitCode -ne 0)
              {
                foreach ($item in $bicepOutput) {
                  $output += "$($item) `r`n"
                }
              }
              else
              {
                echo "Bicep Build Successful for File: $_"
              }
          }
          if ($output.length -gt 0) {
            throw $output
          }

  whatif:
    name: What If
    runs-on:
      self-hosted
    concurrency: r52510r569-tfstate
    environment: alz-r52510r569-plan
    permissions:
      id-token: write
      contents: read
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: Get Bicep Variables
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-variables@main
        with:
          parameters_file_name: ${{ env.PARAMETERS_FILE_NAME }}

      - name: Get On Demand Folder infra-as-code
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-on-demand-folder@main
        with:
          repository: "https://github.com/Azure/ALZ-Bicep"
          releaseArtifactName: "accelerator.zip"
          releaseVersion: "${{ env.RELEASE_VERSION }}"
          sourcePath: "infra-as-code"
          targetPath: "infra-as-code"

      - name: Install Bicep and Update Az Module
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-installer@main

      - name: OIDC Login to Tenant
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: First Deployment Check
        id: firstDeploymentCheck
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-first-deployment-check@main
        with:
          managementGroupId: ${{ env.MANAGEMENT_GROUP_ID }}
      - name: 'What If: Management Groups Deployment'
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-deploy@main
        with:
          displayName: 'Management Groups Deployment'
          templateFilePath: './accelerator/test_modules/managementGroup/managementGroup.bicep'
          templateParametersFilePath: './config/custom-parameters/managementGroup.parameters.all.json'
          managementGroupId: '${{ env.ROOT_PARENT_MANAGEMENT_GROUP_ID }}'
          subscriptionId: ''
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'true'
          firstDeployment: '${{ env.firstDeployment }}'
          whatIfEnabled: 'true'
      - name: 'What If: Management Resource Group Deployment'
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-deploy@main
        with:
          displayName: 'Management Resource Group Deployment'
          templateFilePath: './infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep'
          templateParametersFilePath: './config/custom-parameters/resourceGroupManagement.parameters.all.json'
          managementGroupId: ''
          subscriptionId: '${{ env.MANAGEMENT_SUBSCRIPTION_ID }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'subscription'
          firstRunWhatIf: 'true'
          firstDeployment: '${{ env.firstDeployment }}'
          whatIfEnabled: 'true'
      - name: 'What If: Connectivity Resource Group Deployment'
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-deploy@main
        with:
          displayName: 'Connectivity Resource Group Deployment'
          templateFilePath: './infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep'
          templateParametersFilePath: './config/custom-parameters/resourceGroupConnectivity.parameters.all.json'
          managementGroupId: ''
          subscriptionId: '${{ env.CONNECTIVITY_SUBSCRIPTION_ID }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'subscription'
          firstRunWhatIf: 'true'
          firstDeployment: '${{ env.firstDeployment }}'
          whatIfEnabled: 'true'
      - name: 'What If: Identity Resource Group Deployment'
        uses: microsoft-azure-landing-zones-cd-tests/alz-r52510r569-templates/.github/actions/bicep-deploy@main
        with:
          displayName: 'Identity Resource Group Deployment'
          templateFilePath: './infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep'
          templateParametersFilePath: './config/custom-parameters/resourceGroupIdentity.parameters.all.json'
          managementGroupId: ''
          subscriptionId: '${{ env.IDENTITY_SUBSCRIPTION_ID }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'subscription'
          firstRunWhatIf: 'true'
          firstDeployment: '${{ env.firstDeployment }}'
          whatIfEnabled: 'true'
